{"ast":null,"code":"import { __extends } from \"tslib\";\n/**\n * An error representing a failure of an individual credential provider.\n *\n * This error class has special meaning to the {@link chain} method. If a\n * provider in the chain is rejected with an error, the chain will only proceed\n * to the next provider if the value of the `tryNextLink` property on the error\n * is truthy. This allows individual providers to halt the chain and also\n * ensures the chain will stop if an entirely unexpected error is encountered.\n */\n\nvar ProviderError =\n/** @class */\nfunction (_super) {\n  __extends(ProviderError, _super);\n\n  function ProviderError(message, tryNextLink) {\n    if (tryNextLink === void 0) {\n      tryNextLink = true;\n    }\n\n    var _this = _super.call(this, message) || this;\n\n    _this.tryNextLink = tryNextLink;\n    return _this;\n  }\n\n  return ProviderError;\n}(Error);\n\nexport { ProviderError };","map":{"version":3,"mappings":";AAAA;;;;;;;;;;AASA;AAAA;AAAA;AAAmCA;;AACjC,yBAAYC,OAAZ,EAA6CC,WAA7C,EAAwE;AAA3B;AAAAA;AAA2B;;AAAxE,gBACEC,kBAAMF,OAAN,KAAc,IADhB;;AAA6CG;;AAE5C;;AACH;AAAC,CAJD,CAAmCC,KAAnC","names":["__extends","message","tryNextLink","_super","_this","Error"],"sources":["/home/dalienst/node_modules/@aws-sdk/property-provider/src/ProviderError.ts"],"sourcesContent":["/**\n * An error representing a failure of an individual credential provider.\n *\n * This error class has special meaning to the {@link chain} method. If a\n * provider in the chain is rejected with an error, the chain will only proceed\n * to the next provider if the value of the `tryNextLink` property on the error\n * is truthy. This allows individual providers to halt the chain and also\n * ensures the chain will stop if an entirely unexpected error is encountered.\n */\nexport class ProviderError extends Error {\n  constructor(message: string, public readonly tryNextLink: boolean = true) {\n    super(message);\n  }\n}\n"]},"metadata":{},"sourceType":"module"}